#File name for the csv
waypoint_filename: "/home/anmolk/ese680_ws/src/MPC_AutonomousPlanning/waypoint_CSVs/gtpose.csv"

#Subscriber and publisher topics
pose_topic: "pf/pose/odom"
drive_topic: "drive"
visualization_topic: "visualization_marker"

#Physical parameters
steering_limit: 0.4189
drive_velocity: 2
