#File name for the csv
waypoint_filename: "/home/anmolk/mpc_ws/src/MPC_AutonomousPlanning/waypoint_CSVs/gtpose_fast.csv"

#Subscriber and publisher topics
pose_topic: "gt_pose" #"pf/pose/odom"
drive_topic: "drive"
laser_topic: "scan"
visualization_topic: "visualization_marker"

#Physical parameters
steering_limit: 0.4189
high_velocity: 6
low_velocity: 1

#waypoint parameters
look_ahead_distance: 1.5
