#File name for the csv
waypoint_filename: "/home/anmolk/mpc_ws/src/MPC_AutonomousPlanning/waypoint_CSVs/gtpose_fast.csv"

#Subscriber and publisher topics
pose_topic: "gt_pose" #"pf/pose/odom"
drive_topic: "drive"
laser_topic: "scan"
visualization_topic: "visualization_marker"

#Physical parameters
steering_limit: 0.4189
high_velocity: 6
low_velocity: 1

#waypoint parameters
look_ahead_distance: 1.5

#MPC Tuning parameters
lower_threshold: 1.0 #The threshold that decides if there's an obstacle (should prolly make it velocity based)
midline_threshold: 0.5 #Decides to ignore for large gaps that occurs in cornering
breakneck_steering: 0.4 #Steering for when obstacle on waypoint (needs most tuning, maybe change the method?)
breakneck_steering_threshold: 0.15 #Half-space width for breakneck_steering activation
min_halfspace_width: 0.2 #If halfspace on any side is less than this, set to zero. Prevents running into obstacle. Tune.

Q_matrix_1: 4 #State cost on waypoint error (horizontal)
Q_matrix_2: 4 #State cost on waypoint error (vertical)
R_matrix_1: 2 #State cost on waypoint error (horizontal)
B_matrix: 0.2334 #velocity*deltaT